export const CREATE_DIALOG_REQUEST = 'CREATE_DIALOG_REQUEST';
export const CREATE_DIALOG_SUCCESS = 'CREATE_DIALOG_SUCCESS';
export const CREATE_DIALOG_FAIL = 'CREATE_DIALOG_FAIL';

export const GET_DIALOGS_REQUEST = 'GET_DIALOGS_REQUEST';
export const GET_DIALOGS_SUCCESS = 'GET_DIALOGS_SUCCESS';
export const GET_DIALOGS_FAIL = 'GET_DIALOGS_FAIL';

export const REMOVE_DIALOG_REQUEST = 'REMOVE_DIALOG_REQUEST';
export const REMOVE_DIALOG_SUCCESS = 'REMOVE_DIALOG_SUCCESS';
export const REMOVE_DIALOG_FAIL = 'REMOVE_DIALOG_FAIL';

export const UPDATE_DIALOG_LIST = 'UPDATE_DIALOG_LIST';
